export {default as Header} from './header/Header'
export {default as Footer} from './footer/Footer'
export {default as Loader} from './loader/Loader'
export {default as Slider} from './slider/Slider'
export {default as Services} from './services/Service'
export {default as LatestProduct} from './latestProduct/LatestProduct'